### ISSUE TITLE
[chore] : 운영, 개발 서버 분리

### ISSUE THREAD

**Issue by dlswns2480** [ssu-student-union/homepage-backend#139]
### 📝 Description

- 운영 서버, 개발 서버 분리

---

### 📝 Todo

- [ ] : 개발 서버 ec2, rds 생성
- [ ] : develop 브랜치용 cicd yml 작성
- [ ] : 기존 cicd는 main 브랜치용으로 변경
