### ISSUE TITLE
[feat] : 게시판 별 게시물 상세조회 로직 작성 및 댓글 대댓글 반환 통합, 대댓글 api 개발, 게시물 상태 변경 로직 구현

### ISSUE THREAD

**Issue by chahyunsoo** [ssu-student-union/homepage-backend#44]
### 📝 Description

- 게시물 상세정보 관련 abstract dto 클래스 생성 및 각 게시판 별 공통변수를 abstract dto에 모읍니다.
  - 게시판 별로 다른 변수들은 abstract dto 클래스 상속해서 만들어 놓습니다.
- 게시물 상세정보가 쓰이는 게시판들을 위한 로직 작성 
---

### 📝 Todo

- [x] : 게시물 상세정보 abstract dto 생성 및 학생청원게시물 dto(abstract dto 상속 후)안에 필요한 필드 넣어놓기
- [x] : 게시물 상세정보가 쓰이는 게시판들을 위한 상세조회 로직 추가
- [x] : CategoryCode, BoardCode, GroupCode Enum 값 추가
- [x] : 게시물 상세정보 페이지에 userId에 맞게 본인이 작성한 게시글인지 확인하는 로직 추가
- [x] : 비로그인, 로그인 모든 사용자가 getPost를 할 수 있게 인증 X
- [x] : 일반 댓글과 공식댓글을 구분하기 위해 공식댓글 필드 추가하여 반환
- [x] : 댓글 인기순 최신순 정렬 로직 추가
- [ ] : 대댓글 API 개발 (생성, 수정, 삭제)
- [ ] : 게시물 상태 변경 알고리즘 구현
