### ISSUE TITLE
[fix] : BoardFactory id null 문제 해결 및 자잘한 수정

### ISSUE THREAD

**Issue by chahyunsoo** [ssu-student-union/homepage-backend#67]
### 📝 Description

- BoardFactory의 createMethod 호출 시 BoardImpl을 구현한 class의 id 필드 주입X 문제  
- CategoryCode Enum 값 추가
- OnGoingStatus Enum 값 한국어 변경
- 댓글, 대댓글 수정 lastEditedAt 필드 업데이트 메소드 추가
- 게시물 status 72시간 기준 변경 로직

---

### 📝 Todo

- [x] : BoardFactory 수정 
- [x] : Category Enum 값 추가
- [x] : OnGoingStatus Enum 값 한국어 변경
- [x] : 댓글, 대댓글 수정 lastEditedAt 필드 업데이트 메소드 추가
- [ ] : 게시물 status 72시간 기준 변경 로직
